language: node_js

node_js:
    - stable

install:
    - yarn

before_script:
    - yarn flow
    - yarn lint
    - yarn test

script:
    # Publish canary builds when feature merges back to develop
    - "if [ ${TRAVIS_PULL_REQUEST} = 'false' ]; then yarn canary ; fi"
    # Publish release builds when merges to master
    - "if [ ${TRAVIS_PULL_REQUEST} = 'false' ] && [ ${TRAVIS_BRANCH} = 'master' ]; then yarn release; fi"

# Send coverage data to Coveralls
after_script:
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

branches:
    only:
        - master
        - develop

env:
  global:
    - GH_REPO: github.com/iCHEF/gypcrete.git
