extends: ichef

plugins:
    - flowtype

env:
    browser: true
    es6: true
    jest: true

settings:
    import/resolver:
        babel-module: {}
    import/core-modules:
        - "enzyme"

parserOptions:
    sourceType: module

rules:
    flowtype/define-flow-type: warn
    flowtype/require-valid-file-annotation: warn
    flowtype/use-flow-type: warn
